### ISSUE TITLE
`filter-lines.jar` or other JAR file is corrupted

### ISSUE THREAD

**Issue by sdtemple** [sdtemple/isweep#9]
If this happens to you, please make a comment on this issue! 

I will respond and update the `misc/` with a fresh, uncorrupted version.

**Comment by sdtemple** [comment]
Or, I will make a Python script to do what I request of with the filter-lines program. It is simple filter applications for tab-separated data.

**Comment by sfiddaman** [comment]
Hi Seth, I'm getting the `Error: Invalid or corrupt jarfile ../../software/filter-lines.jar` error. Is there a workaround? Thanks in advance.

**Comment by sdtemple** [comment]
The workaround is to write a simple Python script to filter the IBD segments file. For me, the Java jarfile has been corrupted a few times over two years. Are you in a rush, in which case I could email you a copy of an uncorrupted jarfile? Otherwise, I can try to write the proposed Python script and modifications to the Snakemake rules in a couple weeks.

**Comment by sdtemple** [comment]
Note the branch `threaded-py-io` where I addressed this issue.
